apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rails-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/SOUMOJIT-CHAKRABORTY/xerocodee-devops
    path: ./
    targetRevision: main
    ignore:
      - project.inlang.json
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
